package mx.edu.itl.beans;

import javax.swing.JOptionPane;
import mx.edu.itl.prismas.Cilindro;


public class JCilindroBean extends javax.swing.JPanel
                           implements ICilindro
{
    private Cilindro cilindro = new Cilindro ();

    public JCilindroBean() {
        initComponents();
        
        // Inicializamos los TextField de radio y altura
        jtxtRadio.setText  ( "" + cilindro.getRadio()  );
        jtxtAltura.setText ( "" + cilindro.getAltura() );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpopCilindro = new javax.swing.JPopupMenu();
        jmniResetearValores = new javax.swing.JMenuItem();
        jmniAcercaDe = new javax.swing.JMenuItem();
        jlblImagenCilindro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtRadio = new javax.swing.JTextField();
        jtxtAltura = new javax.swing.JTextField();

        jmniResetearValores.setText("Resetear valores");
        jmniResetearValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniResetearValoresActionPerformed(evt);
            }
        });
        jpopCilindro.add(jmniResetearValores);

        jmniAcercaDe.setText("Acerca de...");
        jmniAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniAcercaDeActionPerformed(evt);
            }
        });
        jpopCilindro.add(jmniAcercaDe);

        setComponentPopupMenu(jpopCilindro);

        jlblImagenCilindro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/edu/itl/iconos/1774091.png"))); // NOI18N

        jLabel1.setText("Radio:");

        jLabel2.setText("Altura:");

        jtxtRadio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtRadio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtRadioFocusLost(evt);
            }
        });

        jtxtAltura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtAltura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtAlturaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlblImagenCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtAltura)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblImagenCilindro, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //--------------------------------------------------------------------------
    
    private void jtxtRadioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtRadioFocusLost
        try {
           double radio = Double.parseDouble ( jtxtRadio.getText() );   
           this.setRadio ( radio );
        } catch ( Exception ex ) {
            JOptionPane.showMessageDialog ( this, "El radio no es un valor numerico" );
            jtxtRadio.requestFocus();
        }
    }//GEN-LAST:event_jtxtRadioFocusLost

    //--------------------------------------------------------------------------
    
    private void jtxtAlturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtAlturaFocusLost
        try {
           double altura = Double.parseDouble ( jtxtAltura.getText() );   
           this.setAltura ( altura );
        } catch ( Exception ex ) {
            JOptionPane.showMessageDialog ( this, "La altura no es un valor numerico" );
            jtxtAltura.requestFocus();
        }        
    }//GEN-LAST:event_jtxtAlturaFocusLost

    private void jmniResetearValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniResetearValoresActionPerformed
        this.setRadio  ( 0.0 );
        this.setAltura ( 0.0 );
        
    }//GEN-LAST:event_jmniResetearValoresActionPerformed

    private void jmniAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniAcercaDeActionPerformed
        JOptionPane.showMessageDialog ( 
            this,
            "JCilindroBean v1.0     \n\n"  +
            "Autores:\n"                   + 
            "Patricia García Almanza   "  +
            " (17130000) \n"               +
            "Juan Gerardo Gacrcía Valenzuela " +
            "(17130029) \n\n\n"       +
            "(C) Derechos reservados 2019",
            "Acerca de",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_jmniAcercaDeActionPerformed

    //--------------------------------------------------------------------------
    
    public JCilindroBean ( double radio, double altura ) {
        this ();  // Invocamos al constructor de default
        cilindro = new Cilindro ( radio, altura );
    }

    //--------------------------------------------------------------------------
    @Override
    public double areaBase() {
        return cilindro.areaBase();
    }
    
    //--------------------------------------------------------------------------
    
    @Override
    public double areaLateral() {
        return cilindro.areaLateral ();
    }

    //--------------------------------------------------------------------------
    
    @Override
    public double areaTotal() {
        return cilindro.areaTotal ();
    }

    //--------------------------------------------------------------------------
    
    @Override
    public double volumen() {
        return cilindro.volumen();
    }

    //--------------------------------------------------------------------------
    
    @Override
    public void setRadio(double radio) {
        jtxtRadio.setText ( "" + radio );
        cilindro.setRadio ( radio );        
    }

    //--------------------------------------------------------------------------
    
    @Override
    public double getRadio() {
        return cilindro.getRadio ();
    }

    //--------------------------------------------------------------------------
    
    @Override
    public void setAltura ( double altura ) {
        jtxtAltura.setText ( "" + altura );
        cilindro.setAltura ( altura );        
    }

    //--------------------------------------------------------------------------
    
    @Override
    public double getAltura() {
        return cilindro.getAltura ();
    }
    
    //--------------------------------------------------------------------------    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlblImagenCilindro;
    private javax.swing.JMenuItem jmniAcercaDe;
    private javax.swing.JMenuItem jmniResetearValores;
    private javax.swing.JPopupMenu jpopCilindro;
    private javax.swing.JTextField jtxtAltura;
    private javax.swing.JTextField jtxtRadio;
    // End of variables declaration//GEN-END:variables

}
