/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mx.edu.itl.beans;

import javax.swing.JOptionPane;
import mx.edu.itl.prismas.PrismaTriangular;

/**
 *
 * @author geras
 */
public class JPrismaTriangularBean extends javax.swing.JPanel implements IPrismaTriangular{

    /** Creates new form JPrismaTriangularBean */
    PrismaTriangular prisma = new PrismaTriangular();
    public JPrismaTriangularBean() {
        initComponents();
        jtxtCateto1.setText( "" + prisma.getC1() );
        jtxtCateto2.setText( "" + prisma.getC2() );
        jtxtAltura.setText ( "" + prisma.getH()  );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    public JPrismaTriangularBean ( double C1, double C2, double altura ) {
        this ();  // Invocamos al constructor de default
        prisma = new PrismaTriangular ( C1, C2, altura );
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpopPT = new javax.swing.JPopupMenu();
        jmniResetearValores = new javax.swing.JMenuItem();
        jmniAcercaDe = new javax.swing.JMenuItem();
        jlblImagenPT = new javax.swing.JLabel();
        jlblCateto1 = new javax.swing.JLabel();
        jtxtCateto1 = new javax.swing.JTextField();
        jlblCateto2 = new javax.swing.JLabel();
        jtxtCateto2 = new javax.swing.JTextField();
        jlblAltura = new javax.swing.JLabel();
        jtxtAltura = new javax.swing.JTextField();

        jmniResetearValores.setText("jMenuItem1");
        jmniResetearValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniResetearValoresActionPerformed(evt);
            }
        });
        jpopPT.add(jmniResetearValores);

        jmniAcercaDe.setText("jMenuItem2");
        jmniAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmniAcercaDeActionPerformed(evt);
            }
        });
        jpopPT.add(jmniAcercaDe);

        setComponentPopupMenu(jpopPT);

        jlblImagenPT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/edu/itl/iconos/PrismaTriangular.png"))); // NOI18N

        jlblCateto1.setText("Cateto1: ");

        jtxtCateto1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtCateto1FocusLost(evt);
            }
        });

        jlblCateto2.setText("Cateto2:");

        jtxtCateto2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtCateto2FocusLost(evt);
            }
        });

        jlblAltura.setText("Altura:");

        jtxtAltura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtAlturaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblImagenPT)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblCateto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtCateto1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCateto2)
                    .addComponent(jlblAltura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jtxtCateto2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCateto1)
                    .addComponent(jtxtCateto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblImagenPT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblCateto2)
                            .addComponent(jtxtCateto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblAltura)
                            .addComponent(jtxtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCateto1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCateto1FocusLost
        try {
           double C1 = Double.parseDouble ( jtxtCateto1.getText() );   
           this.setC1 ( C1 );
        } catch ( Exception ex ) {
            JOptionPane.showMessageDialog ( this, "El cateto 1 no es un valor numerico." );
            jtxtCateto1.requestFocus();
        }
    }//GEN-LAST:event_jtxtCateto1FocusLost

    private void jtxtCateto2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtCateto2FocusLost
        try{
            double C2 = Double.parseDouble( jtxtCateto2.getText() );
            this.setC2( C2 );
        }
        catch( Exception e ){
            JOptionPane.showMessageDialog( this, "El cateto 2 no es un valor numérico." );
            jtxtCateto2.requestFocus();
        }
    }//GEN-LAST:event_jtxtCateto2FocusLost

    private void jtxtAlturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtAlturaFocusLost
        try{
            double H = Double.parseDouble( jtxtAltura.getText() );
            this.setC2( H );
        }
        catch( Exception e ){
            JOptionPane.showMessageDialog( this, "La altura no es un valor numérico." );
            jtxtAltura.requestFocus();
        }
    }//GEN-LAST:event_jtxtAlturaFocusLost

    private void jmniAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniAcercaDeActionPerformed
        JOptionPane.showMessageDialog ( 
            this,
            "JPrismaTriangularBean v1.0     \n\n"  +
            "Autores:\n"                   + 
            "Patricia García Almanza   "  +
            " (17130000) \n"               +
            "Juan Gerardo Gacrcía Valenzuela " +
            "(17130029) \n\n\n"       +
            "(C) Derechos reservados 2019",
            "Acerca de",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_jmniAcercaDeActionPerformed

    private void jmniResetearValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmniResetearValoresActionPerformed
        this.setC1( 0.0 );
        this.setC2( 0.0 );
        this.setH ( 0.0 );
    }//GEN-LAST:event_jmniResetearValoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblAltura;
    private javax.swing.JLabel jlblCateto1;
    private javax.swing.JLabel jlblCateto2;
    private javax.swing.JLabel jlblImagenPT;
    private javax.swing.JMenuItem jmniAcercaDe;
    private javax.swing.JMenuItem jmniResetearValores;
    private javax.swing.JPopupMenu jpopPT;
    private javax.swing.JTextField jtxtAltura;
    private javax.swing.JTextField jtxtCateto1;
    private javax.swing.JTextField jtxtCateto2;
    // End of variables declaration//GEN-END:variables

    @Override
    public double areaBase() {
        return prisma.areaBase();
    }

    @Override
    public double areaLateral() {
        return prisma.areaLateral();
    }

    @Override
    public double areaTotal() {
        return prisma.areaTotal();
    }

    @Override
    public double volumen() {
        return prisma.volumen();
    }

    @Override
    public void setC1( double C1 ) {
        jtxtCateto1.setText( "" + C1 );
        prisma.setC1       ( C1 );
    }

    @Override
    public void setC2( double C2 ) {
        jtxtCateto2.setText( "" + C2 );
        prisma.setC2       ( C2 );
    }

    @Override
    public void setH( double H ) {
        jtxtAltura.setText( "" + H );
        prisma.setH       ( H );
    }

    @Override
    public double getC1() {
        return prisma.getC1();
    }

    @Override
    public double getC2() {
        return prisma.getC2();
    }

    @Override
    public double getH() {
        return prisma.getH();
    }

}
